name: Bug report
description: Create a report to help us improve.
title: "[Component Name] A title for the problem"
labels: ["bug report"]
body:

  - type: input
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Please input
    validations:
      required: true
  
  - type: textarea
    id: reproduceSteps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior. If not, the issue will not be fixed and be closed.
      placeholder: Please input
  
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: Please input
  
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Please input
  
  - type: textarea
    id: remarks
    attributes:
      label: Additional context
      description: Add any other context about the problem here, like screenshot or video record.
      placeholder: Please input
  